version: '3.8'

services:
  db:
    image: postgres:16
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_USER: swiftuser
      POSTGRES_PASSWORD: swiftpass
      POSTGRES_DB: swiftcodesdb
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "swiftuser"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres-data:
